#!/bin/bash

do_cmake_host() {
    if [[ $# -lt 1 ]]; then
        echo_error "Usage: do_cmake_host <srcdir> [...args...]"
        return 1
    fi
    local srcdir="$1"
    shift
    cmake -DCMAKE_INSTALL_PREFIX="$PREFIX" \
          -S "$srcdir" \
          -DCMAKE_C_COMPILER="${BUILD}-gcc" \
          -DCMAKE_CXX_COMPILER="${BUILD}-g++" \
          -DCMAKE_C_FLAGS="$CFLAGS" \
          -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
          "$@"
}

build_host_zstd() {
    mkdir_cd_build zstd && \
    do_cmake_host "${SOURCE_ROOT}/zstd-${ZSTD_VERSION}/build/cmake" \
                  -DZSTD_BUILD_SHARED=OFF \
                  -DZSTD_BUILD_STATIC=ON && \
    do_make_install
}

build_host_gmp() {
    mkdir_cd_build gmp && \
    "${SOURCE_ROOT}/gmp-${GMP_VERSION}/configure" --prefix="$PREFIX" \
                                                  --with-sysroot="$SYSROOT" \
                                                  --disable-rpath \
                                                  --enable-static \
                                                  --disable-shared \
                                                  --enable-silent-rules \
                                                  CFLAGS="$CFLAGS" \
                                                  CXXFLAGS="$CXXFLAGS" \
                                                  CPPFLAGS="$CPPFLAGS" \
                                                  LDFLAGS="$LDFLAGS" \
                                                  --enable-cxx && \
    do_make_install_strip
}

build_host_mpfr() {
    mkdir_cd_build mpfr && \
    do_configure_static "$SOURCE_ROOT/mpfr-${MPFR_VERSION}" \
                        --with-gmp="$PREFIX" && \
    do_make_install_strip
}

build_host_mpc() {
    mkdir_cd_build mpc && \
    "$SOURCE_ROOT/mpc-${MPC_VERSION}/configure" --prefix="$PREFIX" \
                                                --build="$BUILD" \
                                                --host="$HOST" \
                                                --target="$TARGET" \
                                                --enable-static \
                                                --disable-shared \
                                                --enable-silent-rules \
                                                --with-gmp="$PREFIX" \
                                                --with-mpfr="$PREFIX" \
                                                CFLAGS="$CFLAGS" \
                                                CXXFLAGS="$CXXFLAGS" \
                                                CPPFLAGS="$CPPFLAGS" \
                                                LDFLAGS="$LDFLAGS" && \
    do_make_install_strip
}

build_host_isl() {
    mkdir_cd_build isl && \
    do_configure_static "$SOURCE_ROOT/isl-${ISL_VERSION}" \
                        --with-gmp-prefix="$PREFIX" && \
    do_make_install_strip
}

build_host_icu() {
    mkdir_cd_build icu && \
    do_configure_static "${SOURCE_ROOT}/icu-71.1/source" \
                        LDFLAGS="-static-libstdc++ -static-libgcc ${LDFLAGS}" && \
    do_make_install
}

uninstall_host_static_libs() {
    cd "$BUILD_ROOT/zstd" && do_cmake_uninstall && \
    cd "$BUILD_ROOT/gmp" && do_make_uninstall && \
    cd "$BUILD_ROOT/mpfr" && do_make_uninstall && \
    cd "$BUILD_ROOT/mpc" && do_make_uninstall && \
    cd "$BUILD_ROOT/isl" && do_make_uninstall
}